package adventure.adventure.utilities;

public enum DegreesOfEducation {
    EARLY_CHILDHOOD_EDUCATED,
    PRIMARY_EDUCATED,
    LOWER_SECONDARY_EDUCATED,
    UPPER_SECONDARY_EEDUCATED,
    POST_SECONDARY_NON_TERTIARY_EDUCATED,
    ASSOCIATE_DEGREE,
    BACHELOR_DEGREE,GRADUATE_DEGREE,
    DOCTORATE,
    PROFFESIONAL_DEGREE
}
