spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:h2:file:./bazaDanych
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
  h2:
    console:
      enabled: true
      path: /console



