spring:
  datasource:
    url: jdbc:h2:file:./bazaDanych
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
  h2:
    console:
      enabled: true
      path: /console

